# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba3c94dec0b32b83eae1e5630144327f457e6aecaefcdaabc9cfe69a0aed7148ec675d9fe33881b07cdf88be6eacf1aa7123012d1b252c39cdb88f54d0b2f65

test:
  secret_key_base: ad72f07df5d20b58cf8a239ad8307f54592573bf215579ca9f7015cb1557031f5528cb73900304d4f74fd524de99aa16513b02ede4e04e6dc6b2c939252896b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
